### ISSUE TITLE
How to run deepcorrect for unpunctuated text

### ISSUE THREAD

**Issue by adrifloresm** [bedapudi6788/deeppunct#2]
Could you please tell me the steps needed to run deepcorrect, after cloning you repo.

- I would like to use the pre-trained model of your demo. Where is that stored and where do I need to load it? I will like to test is on unpunctuated text.

- What limits the sentence length in/out to 200 ? is it because of the decoder? How can I change that to be let's say 500?

Thank you!

**Comment by bedapudi6788** [comment]
You don't need to clone the repo. Just take a look at the Readme.

I would like to use the pre-trained model of your demo. Where is that stored and where do I need to load it? I will like to test is on unpunctuated text. - Take a look at the readme.



What limits the sentence length in/out to 200 ? is it because of the decoder? How can I change that to be let's say 500? - Even though, you can change the params and use the same checkpoint with sentences more than 500 chars, since the model is only trained on sentences less than 200 chars, it will not be able to generalize well.

**Comment by adrifloresm** [comment]
So is `pip install deepcorrect` the only installation method?

I am interested in training it with my own dataset, and not just using the pre-trained checkpoints. However, the documentation is very limited. I assume the primary intention of your repo is to use it as is?

Thanks

**Comment by bedapudi6788** [comment]
For training take a look at https://github.com/bedapudi6788/txt2txt/ 
That is the repo which contains training instructions and keras model. DeepCorrect is just a wrapper for inference over that.
All this information is clearly mentioned in the Readme file of this repo.

deepcorrect

Pre-trained models for punctuation correction (trained on google news, wikipedia and tatoeba) are available at https://drive.google.com/open?id=1Yd8cJaqfQkrJMbRVWIWtuyo4obTDYu-e

Demo of the punctuation model trained on google news corpus is available at http://bpraneeth.com/projects

This repo uses a seq2seq model written by me in keras with tensorflow backend. The multi-purpose seq2seq model can be found at https://github.com/bedapudi6788/txt2txt/
